# Generated by Django 2.0.5 on 2018-06-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artourquito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monumentosquito',
            name='imagen_antigua',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
