# Generated by Django 2.0.5 on 2018-06-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artourquito', '0002_auto_20180605_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monumentosquito',
            name='imagen_antigua',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
